### ISSUE TITLE
Token related methods should be moved to SmartSheetToken.java

### ISSUE THREAD

**Issue by RichInTheUSA** [RichInTheUSA/MavenSmartSBot#17]
The following methods should be moved out of SmartSheet.java, and into SmartSheetToken.java since they are all related to smartsheet token functionality:

setCurrentToken
setDefaultToken
checkToken
findTokenInMessage   // May want to use a Tokenizer() for this.
setMyToken

**Comment by bpbuell** [comment]
Moved the above functions in the SmartSheetToken.java class and implemented a Tokenizer() on *findTokenInMessage*
